name: localstorage
description: Simple json file-based storage for flutter. Alternative to react-native AsyncStorage
version: 4.0.1+4
homepage: https://github.com/lesnitsky/flutter_localstorage

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any
